import {
  Sparkles, Sun, Scissors, Droplets, Zap, Flower2,
  Layers, Wand2, Syringe, ShieldCheck, Waves, HeartPulse,
} from "lucide-react";

export const SERVICES = [
  { slug: "acne-treatment", title: "Acne Treatment", icon: ShieldCheck,
    short: "Targeted therapies for active acne, scars, and breakouts.",
    benefits: ["Clear, balanced skin", "Reduced inflammation", "Scar prevention"] },
  { slug: "pigmentation", title: "Pigmentation Treatment", icon: Sun,
    short: "Even skin tone with melasma, dark spot & sun damage care.",
    benefits: ["Brighter complexion", "Reduced dark patches", "Long-lasting results"] },
  { slug: "hair-fall", title: "Hair Fall Treatment", icon: Scissors,
    short: "Root-cause analysis and clinical solutions for hair loss.",
    benefits: ["Reduced shedding", "Stronger follicles", "Visible regrowth"] },
  { slug: "prp-therapy", title: "PRP Therapy", icon: Droplets,
    short: "Platelet-rich plasma for hair regrowth and skin rejuvenation.",
    benefits: ["Natural healing", "Improved density", "Glowing skin"] },
  { slug: "laser-hair-reduction", title: "Laser Hair Reduction", icon: Zap,
    short: "FDA-approved diode laser for permanent hair reduction.",
    benefits: ["Smooth skin", "Painless sessions", "Suits all skin tones"] },
  { slug: "anti-aging", title: "Anti-Aging Treatments", icon: Flower2,
    short: "Advanced therapies to restore youthful skin & elasticity.",
    benefits: ["Firmer skin", "Reduced fine lines", "Radiant glow"] },
  { slug: "chemical-peels", title: "Chemical Peels", icon: Layers,
    short: "Medical-grade peels for texture, tone, and clarity.",
    benefits: ["Smoother texture", "Brighter tone", "Minimal downtime"] },
  { slug: "skin-rejuvenation", title: "Skin Rejuvenation", icon: Sparkles,
    short: "Holistic glow-up with personalized treatment plans.",
    benefits: ["Healthy radiance", "Even tone", "Refined pores"] },
  { slug: "botox-fillers", title: "Botox & Fillers", icon: Syringe,
    short: "Subtle, natural-looking enhancement by expert hands.",
    benefits: ["Wrinkle reduction", "Volume restoration", "Natural results"] },
  { slug: "scar-reduction", title: "Scar Reduction", icon: Wand2,
    short: "Advanced microneedling, lasers & subcision for scars.",
    benefits: ["Smoother surface", "Improved tone", "Confidence boost"] },
  { slug: "hydra-facial", title: "Hydra Facial", icon: Waves,
    short: "Deep cleanse + hydration in a single luxury session.",
    benefits: ["Instant glow", "Hydrated skin", "Zero downtime"] },
  { slug: "hair-regrowth", title: "Hair Regrowth Therapy", icon: HeartPulse,
    short: "Mesotherapy, GFC & combo plans for measurable regrowth.",
    benefits: ["Thicker hair", "Reduced fall", "Scalp health"] },
] as const;

export type Service = (typeof SERVICES)[number];
